// Discord Poster
// Uses Discord.js to post formatted reports

const { Client, GatewayIntentBits, EmbedBuilder } = require('discord.js');

class DiscordPoster {
  constructor(botToken, channelId) {
    this.botToken = botToken;
    this.channelId = channelId;
    this.client = new Client({
      intents: [GatewayIntentBits.Guilds]
    });
    this.ready = false;
  }

  async connect() {
    if (this.ready) return;
    
    return new Promise((resolve, reject) => {
      this.client.once('ready', () => {
        console.log(`Discord bot logged in as ${this.client.user.tag}`);
        this.ready = true;
        resolve();
      });
      
      this.client.once('error', reject);
      this.client.login(this.botToken).catch(reject);
    });
  }

  async disconnect() {
    if (this.ready) {
      await this.client.destroy();
      this.ready = false;
    }
  }

  async postReport(category, tweet, replySuggestions) {
    const channel = await this.client.channels.fetch(this.channelId);
    if (!channel) {
      throw new Error('Discord channel not found');
    }

    const embed = new EmbedBuilder()
      .setColor(this.getCategoryColor(category))
      .setTitle(`🔥 ${category.toUpperCase()}`)
      .setURL(tweet.url)
      .setDescription(this.formatTweetText(tweet.text))
      .setAuthor({
        name: `@${tweet.author?.username || 'unknown'}`,
        iconURL: 'https://abs.twimg.com/icons/apple-touch-icon-192x192.png'
      })
      .addFields(
        { name: '❤️ Likes', value: tweet.metrics.likes.toLocaleString(), inline: true },
        { name: '🔄 Retweets', value: tweet.metrics.retweets.toLocaleString(), inline: true },
        { name: '💬 Replies', value: tweet.metrics.replies.toLocaleString(), inline: true }
      )
      .setTimestamp(new Date(tweet.createdAt))
      .setFooter({ text: `Engagement Score: ${tweet.engagementScore.toLocaleString()}` });

    // Add reply suggestions as fields
    replySuggestions.forEach((reply, index) => {
      embed.addFields({
        name: `💡 Reply Option ${index + 1}`,
        value: reply
      });
    });

    await channel.send({ embeds: [embed] });
  }

  async postHeader(hour, bangkokTime) {
    const channel = await this.client.channels.fetch(this.channelId);
    
    const embed = new EmbedBuilder()
      .setColor(0x0d9488) // Teal
      .setTitle(`📊 Viral Tweets Report`)
      .setDescription(`Top tweets from the last hour\n🕐 Bangkok: ${bangkokTime} | UTC: ${hour}:00`)
      .setTimestamp();

    await channel.send({ embeds: [embed] });
    await channel.send('─'.repeat(40)); // Separator
  }

  async postFooter() {
    const channel = await this.client.channels.fetch(this.channelId);
    await channel.send('─'.repeat(40));
    await channel.send('*Report generated by The Department of Quietly Getting Things Done*');
  }

  async postNoTweetsMessage() {
    const channel = await this.client.channels.fetch(this.channelId);
    const embed = new EmbedBuilder()
      .setColor(0xf59e0b) // Amber
      .setTitle('⚠️ No Viral Tweets Found')
      .setDescription('Fetched tweets but none met the threshold (10+ likes, 100+ followers).\nTry again in an hour.')
      .setTimestamp();
    await channel.send({ embeds: [embed] });
  }

  formatTweetText(text) {
    // Truncate if too long for Discord embed
    if (text.length > 400) {
      return text.substring(0, 397) + '...';
    }
    return text;
  }

  getCategoryColor(category) {
    const colors = {
      'tech': 0x3b82f6,    // Blue
      'crypto': 0xf59e0b,   // Amber/Gold  
      'ai': 0x8b5cf6        // Purple
    };
    return colors[category.toLowerCase()] || 0x6b7280;
  }
}

module.exports = DiscordPoster;
